title: Goodbye Glaciers
email: patrick.schmitt@uibk.ac.at
description: >- # this means to ignore newlines until "baseurl:"
  Website for the goodbye glaciers project.
#twitter_username: username
#github_username: username
#baseurl: ""
#url: "https://goodbye-glaciers.info"
baseurl: "/goodbye_glaciers" # GitHub repository name
url: "https://lilianschuster.github.io" # Your GitHub Pages domain



minimal_mistakes_skin: default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

collections:
  glaciers:
    output: true
  events:
    output: true
    sort_by: date

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pat-schmitt/goodbye_glaciers/"
atom_feed:
  hide: true
 
defaults:
  - scope:
      path: ""
      type: "glaciers"
    values:
      layout: glacier
  - scope:
      path: ""
    values:
      layout: splash
