name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.3 # Use a compatible Ruby version
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to Main Branch
      run: |
        # Clean untracked files but keep the .git folder
        rm -rf !(._site|.git|.)
        # Move the built site to the root
        mv _site/* .
        # Remove the _site directory itself
        rm -rf _site
        # Commit and push changes
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy updated site"
        git push origin main --force

